Repository zoriya/Kyoo, pull requests merged in 2024-08, with the labels that each got.

#582 Front: Fix Media Metadata
  front/packages/ui/src/player/index.tsx
  front/packages/ui/src/player/media-session.tsx
  front/packages/ui/src/player/state.tsx
Labels: enhancement, webapp

#584 Front: Hide Ratings with value equals 0
  front/packages/ui/src/details/header.tsx
Labels: webapp

#590 Front: Add Gradient behind navbar if transparent
  front/apps/web/src/pages/_app.tsx
  front/packages/ui/src/layout.tsx
  front/packages/ui/src/navbar/index.tsx
Labels: bug, webapp

#593 Backport fixes from #592
  transcoder/src/filestream.go
  transcoder/src/keyframes.go
  transcoder/src/metadata.go
Labels: transcoder

#594 Update from pacakges & make android seek better to use
  front/Dockerfile
  front/Dockerfile.dev
  front/apps/mobile/app.config.ts
  front/apps/mobile/app/(app)/_layout.tsx
  front/apps/mobile/package.json
  front/apps/web/next.config.js
  front/apps/web/package.json
  front/package.json
  front/packages/models/package.json
  front/packages/primitives/package.json
  front/packages/ui/package.json
  front/packages/ui/src/downloads/page.tsx
  front/packages/ui/src/player/components/right-buttons.tsx
  front/packages/ui/src/player/index.tsx
  front/packages/ui/src/player/media-session.tsx
  front/packages/ui/src/player/state.tsx
  front/packages/ui/src/player/video.web.tsx
  front/yarn.lock
Labels: webapp

#595 Front: Improve readability in menus
  front/packages/primitives/src/menu.web.tsx
Labels: webapp

#601 Add custom schema handling for gocoder
  front/packages/primitives/src/snackbar.tsx
  front/packages/ui/src/navbar/icon.tsx
  transcoder/.env.example
  transcoder/src/keyframes.go
  transcoder/src/metadata.go
Labels: transcoder

#602 Fix playback with avi files missing PTS
  transcoder/Dockerfile
  transcoder/Dockerfile.dev
  transcoder/src/keyframes.go
  transcoder/src/stream.go
Labels: bug, transcoder
